### PR TITLE
feat: update traefik to 2.5.0

### PR DESCRIPTION
**Pull request by sparkoo**
Signed-off-by: Michal Vala <mvala@redhat.com>

### What does this PR do?
update traefik to 2.5.0

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/20142

### How to test this PR?

Prerequisite: use template from PR branch -> clone `https://github.com/sparkoo/che-operator/tree/gh20142-updateTraefik` and build the templates https://github.com/eclipse-che/che-operator#deploy-che-operator-with-chectl-using---installer-operator-flag. Then always deploy with these templates.

1. deploy Che with `server.serverExposureStrategy: single-host`
2. check that traefik container in gateway is 2.5.0
3. start a workspace

_

1. deploy Che with devworkspaces enabled
2. check that traefik container in gateway is 2.5.0
3. start a workspace

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [Custom resource definition file is up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#updating-custom-resource-definition-file)
- [x] [OLM bundles are up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#update-olm-bundle)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by skabashnyuk — APPROVED** [review]

**Review by metlos — APPROVED** [review]

**Comment by tolusha** [comment]
@sparkoo 
To have openshift tests passed, pls revert `RELATED_IMAGE_single_host_gateway_native_user_mode` to `manager.yaml` (just this env var) and remove it in another PR then.

**Review by mmorhun — APPROVED** [review]

**Review by AndrienkoAleksandr — APPROVED** [review]

**Pull request merged**
