### PR TITLE
fix: Do not delete internal backup server on backup CR deletion

### PR DESCRIPTION
**Pull request by mmorhun**
### What does this PR do?
Do not set controller references on objects created by backup controller that are related to internal backup server in order to be able to reuse it for several backups in a row.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/18703
https://github.com/eclipse/che/issues/19932

### How to test this PR?
1. Schedule a backup by creating backup custom resource:
```yaml
apiVersion: org.eclipse.che/v1
kind: CheClusterBackup
metadata:
  name: eclipse-che-backup
spec:
  useInternalBackupServer: true
```
2. Delete created backup CR after backup successfully finishes.
3. Make sure that internal backup server resources (deployment, backup server config and secrets) are not deleted.
4. Request another backup by creating backup CR again
5. Check that new backup created.

### PR Checklist
          
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [Custom resource definition file is up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#updating-custom-resource-definition-file)
- [x] [Nightly OLM bundle is up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#update-nightly-olm-bundle)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by AndrienkoAleksandr — APPROVED** [review]

**Review by tolusha — APPROVED** [review]

**Comment by tolusha** [comment]
@mmorhun 
I would like to see some unit tests

**Comment by mmorhun** [comment]
Tests are failing due to https://github.com/eclipse/che/issues/20072

**Pull request merged**
