### PR TITLE
chore: Update DevWorkspace Operator dependency to v0.12.3

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
Updates the DevWorkspace Operator dependency to v0.12.3 in order to pick up changes from commit https://github.com/devfile/devworkspace-operator/commit/69be85cdf34d1cb7d4aafc85cdd9c8a809e27a09

This resolves an issue where the DevWorkspaceRouting reconciler, as used by the Che Operator, can panic due to the internal config structure used by DWO not being set up.

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
No issue created (yet)

### How to test this PR?
Changes from this PR are built into quay.io/amisevsk/che-operator:dwo-0.12.3

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [N/A] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [Custom resource definition file is up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#updating-custom-resource-definition-file)
- [x] [OLM bundles are up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#update-olm-bundle)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [N/A] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [N/A] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by amisevsk** [comment]
To test the issue being fixed:
* Start a Devfile v2 workspace
* Find a route/ingress/service used by the workspace
* Edit the `che.routing.controller.devfile.io/component-name` annotation
(though note that this will put the `next` Che Operator into a crash loop until the annotation is fixed without this PR.

**Review by ibuziuk — APPROVED** [review]

**Pull request merged**
