### PR TITLE
Gh19707 secure workspace

### PR DESCRIPTION
**Pull request by sparkoo**
### What does this PR do?
Secures workspace route so only owner has access to it.

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/19707

### How to test this PR?

che-operator image `quay.io/mvala/che-operator:gh19707-secureWorkspace`

1. deploy on openshift with devworkspaces enabled 
2. login as some user and start a devworkspace
3. copy workspace url or get it from devworkspace object `kubectl get dw -n user1-che`
4. login as different user and try to access the workspace, you should get Unauthorized 403.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [Custom resource definition file is up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#updating-custom-resource-definition-file)
- [x] [OLM bundles are up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#update-olm-bundle)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by skabashnyuk** [comment]
Works for me.
From opentlc-mgr
Знімок екрана 2021-08-18 о 15 32 29
from user1
Знімок екрана 2021-08-18 о 15 32 21

**Review by tolusha — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]

**Comment by xbaran4** [comment]
Works for me as well.
user7:
image
user10:
image

**Review by xbaran4 — APPROVED** [review]

**Pull request merged**
