### PR TITLE
build: Enable Image Puller for tests

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatolii Bazko <abazko@redhat.com>

### What does this PR do?
Enable Image Puller for tests

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/20032

### How to test this PR?

N/A

### PR Checklist
          
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [Custom resource definition file is up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#updating-custom-resource-definition-file)
- [ ] [Nightly OLM bundle is up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#update-nightly-olm-bundle)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by tolusha** [comment]
time="2021-07-22T07:39:22Z" level=info msg="There is no PackageManifest for the Kubernetes Image Puller Operator.  Install the Operator Lifecycle Manager and the Community Operators Catalog"

**Comment by tolusha** [comment]
time="2021-07-22T10:45:43Z" level=info msg="Waiting 15 seconds for kubernetesimagepullers.che.eclipse.org API"

**Review by AndrienkoAleksandr — APPROVED** [review]

**Comment by flacatus** [comment]
Next image is not working for me in my RHPDS cluster is crashing on start the operator

**Comment by flacatus** [comment]
Also I see errors like:

```log
time="2021-07-23T20:38:46Z" level=error msg="Error updating Subscription: subscriptions.operators.coreos.com \"kubernetes-imagepuller-operator\" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update"
time="2021-07-23T20:38:50Z" level=info msg="Updating Subscription"
time="2021-07-23T20:38:50Z" level=error msg="Error updating Subscription: subscriptions.operators.coreos.com \"kubernetes-imagepuller-operator\" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update"

```

**Review by mmorhun — APPROVED** [review]

**Review by flacatus — APPROVED** [review]

**Pull request merged**
