### PR TITLE
Updated oc-test-happy-path.sh according to new test scripts in "Che" project

### PR DESCRIPTION
**Pull request by nallikaea**
### What does this PR do?
According to task  #[22043](https://github.com/eclipse/che/pull/22043) test scripts were updated, necessary changes added to this repository.
PR: [#22052](https://github.com/eclipse/che/pull/22052)

The old npm script "test-empty-workspace-devworkspace-happy-path-code" runs one test spec file - "EmptyWorkspace.spec.ts" from the test [directory](https://github.com/eclipse/che/tree/main/tests/e2e/tests/devfiles/che-code) and uses hard-coded mocha config.
It was replaced with "test-all-devfiles" which uses new dynamic mocha config and will run the same file if variable "USERSTORY=EmptyWorkspace" or all test specs in the test directory if variable not set. 

### Screenshot/screencast of this PR

N/A

### How to test this PR?

Run happy-pass PR check.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [Development resource are up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#update-development-resources)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by tolusha** [comment]
@nallikaea 
Could you describe what `test-all-devfiles` is about?

**Comment by tolusha** [comment]
@nallikaea 

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/eclipse-che_che-operator/1641/pull-ci-eclipse-che-che-operator-main-v12-devworkspace-happy-path/1637790262698708992

```
/tmp/e2e/node_modules/mocha/lib/cli/config.js:80
    throw createUnparsableFileError(
    ^
Error: Unable to read/parse mocha-all-devfiles-.json: Error: ENOENT: no such file or directory, open 'mocha-all-devfiles-.json'
    at createUnparsableFileError (/tmp/e2e/node_modules/mocha/lib/errors.js:514:13)
    at exports.loadConfig (/tmp/e2e/node_modules/mocha/lib/cli/config.js:80:11)
    at loadRc (/tmp/e2e/node_modules/mocha/lib/cli/options.js:162:21)
    at loadOptions (/tmp/e2e/node_modules/mocha/lib/cli/options.js:234:20)
    at Object.<anonymous> (/tmp/e2e/node_modules/mocha/bin/mocha:27:14)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'ERR_MOCHA_UNPARSABLE_FILE'
```

**Comment by nallikaea** [comment]
> @nallikaea
> 
> https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/eclipse-che_che-operator/1641/pull-ci-eclipse-che-che-operator-main-v12-devworkspace-happy-path/1637790262698708992
> 
> ```
> /tmp/e2e/node_modules/mocha/lib/cli/config.js:80
>     throw createUnparsableFileError(
>     ^
> Error: Unable to read/parse mocha-all-devfiles-.json: Error: ENOENT: no such file or directory, open 'mocha-all-devfiles-.json'
>     at createUnparsableFileError (/tmp/e2e/node_modules/mocha/lib/errors.js:514:13)
>     at exports.loadConfig (/tmp/e2e/node_modules/mocha/lib/cli/config.js:80:11)
>     at loadRc (/tmp/e2e/node_modules/mocha/lib/cli/options.js:162:21)
>     at loadOptions (/tmp/e2e/node_modules/mocha/lib/cli/options.js:234:20)
>     at Object.<anonymous> (/tmp/e2e/node_modules/mocha/bin/mocha:27:14)
>     at Module._compile (node:internal/modules/cjs/loader:1191:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
>     at Module.load (node:internal/modules/cjs/loader:1069:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:904:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
>   code: 'ERR_MOCHA_UNPARSABLE_FILE'
> ```

thank you, @tolusha. this is expected result, because PR https://github.com/eclipse/che/pull/22052 has not merged yet

**Comment by tolusha** [comment]
@nallikaea 
Could you check please
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/eclipse-che_che-operator/1641/pull-ci-eclipse-che-che-operator-main-v12-devworkspace-happy-path/1638429800630587392/artifacts/devworkspace-happy-path/devworkspace-happy-path/

**Comment by dmytro-ndp** [comment]
@nallikaea : it seems there is a mistake in - redundant `exit 1` https://github.com/eclipse/che/blame/main/tests/e2e/configs/sh-scripts/initDevfileTests.sh#L23

Also, it's not clear why $TS_SELENIUM_EDITOR is empty when execute "initDevfileTests.sh".

@ScrewTSW, @musienko-maxim: cc

**Comment by nallikaea** [comment]
https://github.com/eclipse/che/pull/22084

fix merged

**Pull request merged**
