### PR TITLE
Copy 7.29.1 csv to main

### PR DESCRIPTION
**Pull request by mkuznyetsov**

### CODE REVIEW

**Review by tolusha — APPROVED** [review]

**Comment by tolusha** [comment]
Operator logs shows that Eclipse Che has been deployed succesfully but chectl failed with
```
INFO[2021-04-23T14:35:47Z] [14:35:40] → Error: connect ETIMEDOUT 54.173.180.196:6443 
```

**Comment by flacatus** [comment]
@tolusha Seems like platform error not related with chectl

**Comment by tolusha** [comment]
Yes, it seems problem with platform but chectl can be improved as well  https://github.com/eclipse/che/issues/19674

**Pull request merged**
