### PR TITLE
fix: Removing '-Dcom.redhat.fips=false' from the default JAVA_OPTS

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?

Removing '-Dcom.redhat.fips=false' from the default JAVA_OPTS 

In the latest Dev Spaces release the latest 6.8.1 version of k8s client is used which is FIPS compatible - https://github.com/fabric8io/kubernetes-client/issues/3582 and there is no need to disable fips via `-Dcom.redhat.fips=false` on the che-server end.

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-4592

### How to test this PR?

- Provision cluster with FIPS enabled (the easiest way to do it is via clusterbot `launch 4.13 azure,fips`)
- Check that the FIPS mode is enabled on the cluster via `oc get cm cluster-config-v1 -n kube-system -o json | jq -r '.data' | grep -i "fips"` command

Screenshot 2023-11-09 at 16 45 11

- Install the latest version of Dev Spaces 3.9.0 / 3.9.1 and create a CR with updated JAVA_OPTS without `-Dcom.redhat.fips=false`

```
spec:
  components:
    cheServer:
      extraProperties:
        JAVA_OPTS : '-XX:MaxRAMPercentage=85.0'
```

- Check the value of the `JAVA_OPTS` env var in che-server / devspaces pod as well as in the `che` configmap - it should be `-XX:MaxRAMPercentage=85.0` 

Screenshot 2023-11-09 at 16 56 07

- start / stop a few workspace and verify that workspace startup has no issues / no errors in the che-server logs

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [Development resource are up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#update-development-resources)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by tolusha — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
@ibuziuk: thanks for the detailed "**How to test this PR?**" section in description.
The only thing I couldn't find was where to get che-operator images built from this PR to test.
Did I miss something? :-)

**Comment by tolusha** [comment]
@dmytro-ndp 
To test the PR, please
1. checkout the corresponding branch
2. run `build/scripts/oc-tests/oc-test-operator.sh`

**Comment by ibuziuk** [comment]
@dmytro-ndp I believe it is important to test that Dev Spaces 3.8 can not run without `-Dcom.redhat.fips=false` whereas 3.9 can. 

On Dev Spaces 3.8 if this flag is removed, che-server should fail to start with the following error:


```
Caused by: KeyManagementException: FIPS mode: only SunJSSE TrustManagers may be used
	at java.base/SSLContextImpl.chooseTrustManager(SSLContextImpl.java:133)
	at java.base/SSLContextImpl.engineInit(SSLContextImpl.java:95)
	at java.base/SSLContext.init(SSLContext.java:297)
	at SSLUtils.sslContext(SSLUtils.java:85)
	at HttpClientUtils.applyCommonConfiguration(HttpClientUtils.java:206)
```

**Comment by dmytro-ndp** [comment]
@tolusha : thanks for the answer.
I hadn't managed to build che-operator image locally on OS Dedora, because `build/scripts/oc-tests/oc-test-operator.sh` script execution stuck:
```
[ndp@fedora che-operator]$ build/scripts/oc-tests/oc-test-operator.sh
++++++ readlink -f build/scripts/oc-tests/oc-test-operator.sh
+++++ dirname /home/ndp/projects/ibuziuk/che-operator/build/scripts/oc-tests/oc-test-operator.sh
++++ dirname /home/ndp/projects/ibuziuk/che-operator/build/scripts/oc-tests
+++ dirname /home/ndp/projects/ibuziuk/che-operator/build/scripts
++ dirname /home/ndp/projects/ibuziuk/che-operator/build
+ export OPERATOR_REPO=/home/ndp/projects/ibuziuk/che-operator
+ OPERATOR_REPO=/home/ndp/projects/ibuziuk/che-operator
+ trap catchFinish EXIT SIGINT
+ runTests
+ . /home/ndp/projects/ibuziuk/che-operator/build/scripts/olm/test-catalog-from-sources.sh --verbose
++ set -e
+++++++ readlink -f /home/ndp/projects/ibuziuk/che-operator/build/scripts/olm/test-catalog-from-sources.sh
++++++ dirname /home/ndp/projects/ibuziuk/che-operator/build/scripts/olm/test-catalog-from-sources.sh
+++++ dirname /home/ndp/projects/ibuziuk/che-operator/build/scripts/olm
++++ dirname /home/ndp/projects/ibuziuk/che-operator/build/scripts
+++ dirname /home/ndp/projects/ibuziuk/che-operator/build
++ OPERATOR_REPO=/home/ndp/projects/ibuziuk/che-operator
++ source /home/ndp/projects/ibuziuk/che-operator/build/scripts/oc-tests/oc-common.sh
+++ export NAMESPACE=eclipse-che
+++ NAMESPACE=eclipse-che
+++ export ARTIFACTS_DIR=/tmp/artifacts-che
+++ ARTIFACTS_DIR=/tmp/artifacts-che
+++ export ECLIPSE_CHE_PACKAGE_NAME=eclipse-che
+++ ECLIPSE_CHE_PACKAGE_NAME=eclipse-che
+++ export ECLIPSE_CHE_CATALOG_SOURCE_NAME=eclipse-che
+++ ECLIPSE_CHE_CATALOG_SOURCE_NAME=eclipse-che
+++ export ECLIPSE_CHE_SUBSCRIPTION_NAME=eclipse-che
+++ ECLIPSE_CHE_SUBSCRIPTION_NAME=eclipse-che
++ export ECLIPSE_CHE_ROOT_DIR=/tmp/eclipse-che
++ ECLIPSE_CHE_ROOT_DIR=/tmp/eclipse-che
++ export CATALOG_DIR=/tmp/eclipse-che/olm-catalog/next
++ CATALOG_DIR=/tmp/eclipse-che/olm-catalog/next
++ export BUNDLE_DIR=/tmp/eclipse-che/bundle
++ BUNDLE_DIR=/tmp/eclipse-che/bundle
++ export CA_DIR=/tmp/eclipse-che/certificates
++ CA_DIR=/tmp/eclipse-che/certificates
+++ make bundle-name CHANNEL=next
```

**Comment by tolusha** [comment]
> chectl: command not found
It requires `chectl`

**Comment by dmytro-ndp** [comment]
@tolusha: something went wrong on my local machine, and I hadn't managed building che-operator image.
I would be grateful if you could build the image from this PR and share it with me.

**Comment by tolusha** [comment]
Please use the following image to test `quay.io/abazko/operator:CRW-4592`

**Comment by ibuziuk** [comment]
> something went wrong on my local machine, and I hadn't managed building che-operator image.
@dmytro-ndp why are you using local machine and not the dogfooding instance? `make docker-build docker-push IMG=` should work I belive

**Comment by dmytro-ndp** [comment]
@ibuziuk :
> @dmytro-ndp why are you using local machine and not the dogfooding instance?

Because I didn't know that it was possible to build che-operator image on Che dogfooding instance
Thanks to your hint I have successfully built quay.io/dmytro_ndp/che-operator:pr-1777 on Che dogfooding.

I have a question about PR testing.
PR description said that we should apply next che cluster patch when install Dev Spaces:
```
spec:
  components:
    cheServer:
      extraProperties:
        JAVA_OPTS : '-XX:MaxRAMPercentage=85.0'
```

Is it really needed taking into account that there is already `DefaultJavaOpts = "-XX:MaxRAMPercentage=85.0"` [in pkg/common/constants/constants.go](https://github.com/eclipse-che/che-operator/pull/1777/files#diff-0501a6e1a48b49ee780c6183edb77b222c1e4f5195e3521170c8847380e69d9d) ?

**Comment by ibuziuk** [comment]
@dmytro-ndp no worries, my point was that we should use Eclipse Che for development / verification as much as possible ;-)

> PR description said that we should apply next che cluster patch when install Dev Spaces

PR description is saying about testing Dev Spaces 3.9.1 and 3.8.0. For upstream Eclipse Che verification patching CR is not needed, but it is important to note that the issue was reproducible only on Dev Spaces, not Eclipse Che. That's great to verify upstream functionality, but before merging this PR please also do the verification of Dev Spaces according to the PR description.

**Comment by dmytro-ndp** [comment]
@ibuziuk : I have successfully tested Dev Spaces 3.9.1 deployed using quay.io/dmytro_ndp/che-operator:pr-1777 built from this PR:
> - Check that the FIPS mode is enabled on the cluster

if was enabled
<details>
<summary>Screenshot</summary>

Screenshot from 2023-11-15 21-01-41

</details>

> - Check the value of the JAVA_OPTS env var in che-server / devspaces pod as well as in the che configmap - it should be -XX:MaxRAMPercentage=85.0

<details>
<summary>Screenshot</summary>

Screenshot from 2023-11-15 20-52-21

</details>

> - start / stop a few workspace and verify that workspace startup has no issues / no errors in the che-server logs
Quarkus and Lombok workspaces has started successfully
<details>
<summary>Screenshot</summary>

Screenshot from 2023-11-15 20-59-50

</details>

TODO: testing DS 3.8.0 / Eclipse Che next.

**Comment by dmytro-ndp** [comment]
@ibuziuk : about
> On Dev Spaces 3.8 if this flag is removed, che-server should fail to start

DS 3.8.0 server DID NOT fail to start on OCP 4.14 azure with fips, and `JAVA_OPTS=-XX:MaxRAMPercentage=85.0`:

<details>
 <summary>oc get cm cluster-config-v1 -n kube-system -o json | jq -r '.data' | grep -i "fips" command</summary>

Screenshot from 2023-11-16 15-03-02

</details>

<details>
 <summary>JAVA_OPTS env var in devspaces pod</summary>

Screenshot from 2023-11-16 14-59-53

</details>

<details>
 <summary>devspaces pod logs</summary>

Screenshot from 2023-11-16 15-02-16

</details>

**Comment by ibuziuk** [comment]
@dmytro-ndp thanks for the review, this does not look expected. Would it be possible to try the same flow against 3.7?

**Comment by dmytro-ndp** [comment]
@ibuziuk: DS 3.7.2 server had also successfully started on OCP 4.14 azure with fips, and `JAVA_OPTS=-XX:MaxRAMPercentage=85.0`, and I was successfully create workspace in there.

Here server logs: https://gist.github.com/dmytro-ndp/1c0d536000e27e6b893f9c52552b502f

Do you think it could be related to OCP version = **4.14**?

**Review by dmytro-ndp — APPROVED** [review]
PR looks good to merge, because _Eclipse Che Next_ has been successfully deployed to _OCP 4.13 with FIPS enabled_ using "**quay.io/dmytro_ndp/che-operator:pr-1777**" image built from this PR (https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/Che/job/ocp/job/basic/job/install-che-to-ocp/89/) as well as _Dev Spaces 3.9.1_ to _OCP 4.14 with FIPS enabled_.

**Comment by ibuziuk** [comment]
@dmytro-ndp Thanks for the review, I was able to reproduce the error back in the summer - https://issues.redhat.com/secure/attachment/13005118/13005118_devspaces-56c78b84-ddb6d-devspaces.log

`Eclipse Che Api Core: Build info '7.67.1.redhat-00004' scmRevision 'ed152183c9f474dd6ea93daa5883b9a0901bd257' `

Which Dev Spaces version does it correspond to?

**Comment by dmytro-ndp** [comment]
@ibuziuk : I have tested DS 3.7.2 with `Eclipse Che Api Core: Build info '7.67.1.redhat-00009' scmRevision '8cb9328e36c05d7aa07ece1f23d5f3ebc2f1f7fc' implementationVersion '7.67.1.redhat-00009'`

> https://github.com/eclipse-che/che-operator/pull/1777#issuecomment-1815484567

**Comment by ibuziuk** [comment]
ack, thanks
going to re-test against 3.7.0 - the issue should be reproducible against this version

**Comment by dmytro-ndp** [comment]
@ibuziuk : I will check on DS 3.7.1 on my side.

**Comment by dmytro-ndp** [comment]
@ibuziuk : if you will test on OCP 4.13, here the command to install DS 3.7.0 specifically:
```
oc create -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: devspaces
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Manual
  name: devspaces
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: devspacesoperator.v3.7.0
EOF
```

**Comment by ibuziuk** [comment]
I am able to reproduce the issue on cluster bot aka`launch 4.12 aws,amd64,fips` with 3.7.0

**Comment by dmytro-ndp** [comment]
@ibuziuk : I have also reproduced the error on DS 3.7.1 deployed to 4.13 azure,fips:
https://gist.github.com/dmytro-ndp/8ac3afb4883ed6b1e8f33fb33331511a
```
2023-11-21 17:06:23,461[main] [ERROR] [o.a.c.c.C.[.[localhost].[/api] 175] - Exception sending context initialized event to listener instance of class [org.eclipse.che.inject.CheBootstrap]
com.google.inject.CreationException: Unable to create injector, see the following errors:
1) [Guice/ErrorInjectingConstructor]: KubernetesClientException: An error has occurred.
at CheServerKubernetesClientFactory.<init>(CheServerKubernetesClientFactory.java:31)
at CheServerKubernetesClientFactory.class(CheServerKubernetesClientFactory.java:31)
at UserPermissionConfigurator.<init>(UserPermissionConfigurator.java:45)
\_ for 2nd parameter
at UserPermissionConfigurator.class(UserPermissionConfigurator.java:45)
while locating UserPermissionConfigurator
while locating NamespaceConfigurator annotated with @Element(setName=,uniqueId=72, type=MULTIBINDER, keyType=)
```
Dev Spaces 3.7.1 despaces server had `Eclipse Che Api Core: Build info '7.67.1.redhat-00005' scmRevision 'efcc659d6d75025fe22d8a0c811a429f534de9d8' implementationVersion '7.67.1.redhat-00005'`

-----------

More info about DS 3.7.2, where the problem HAS NOT been reproduced - it is a CVE fix which was aimed to resolve https://issues.redhat.com/browse/CRW-4792

**Comment by ibuziuk** [comment]
interesting, if the problem is not reproducible in 3.7.2 than it is related to https://github.com/eclipse-che/che-server/pull/540/files and not to fabric8-k8s-client update https://github.com/fabric8io/kubernetes-client/issues/3582

**Pull request merged**
