### PR TITLE
Use errors middleware to redirect on idled workspace after 4 seconds

### PR DESCRIPTION
**Pull request by dkwon17**
Signed-off-by: David Kwon <dakwon@redhat.com>

### What does this PR do?
Alternative PR to https://github.com/eclipse-che/che-operator/pull/1386. The main difference is that this PR uses the Errors Traefik middleware.

### Screenshot/screencast of this PR
In this gif we see that:
1. Workspace is stopped
2. IDE page is refreshed
3. Instead of a 504 error, the user is redirected to the dashboard after 4 seconds

errorsmiddleware

### What issues does this PR fix or reference?

Part of https://github.com/eclipse/che/issues/20599. In another PR, maybe we can redirect the user to some error page provided by the dashboard.

### How to test this PR?

 
 Tested on CRC with the following:

1. Deploy
```bash
chectl server:deploy \
     --platform crc\
     --che-operator-image quay.io/dkwon17/che-operator:useerrorsmiddleware
```

2. Open the dashboard with the URL provided by the output from chectl.
3. Start a workspace, and wait until the editor opens.
4. Stop the workspace.
5. Refresh the editor. You should be redirected to the dashboard after 4 seconds where you can start the workspace again.
### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [Custom resource definition file is up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#updating-custom-resource-definition-file)
- [ ] [OLM bundles are up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#update-olm-bundle)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by dkwon17** [comment]
The workspace page is `<CHE_HOST>/dashboard/#/workspaces` is that right?

On the Traeffik side with the Traeffik errors middleware, the content after the `#` is considered a URL fragment and is ignored because it is a browser-concept: https://github.com/traefik/traefik/issues/9022#issuecomment-1129715356

To support redirection to the workspaces page, I think we would need to make some changes where the dashboard server receives the HTTP request.

**Comment by dkwon17** [comment]
There is a bug somewhere in this implementation. When restarting an idled workspace, instead of opening the IDE, I'm redirected to the dashboard. I am investigating

**Comment by dkwon17** [comment]
This PR is ready to review. This PR adds two middlewares ([errors](https://doc.traefik.io/traefik/middlewares/http/errorpages/) and [headers](https://doc.traefik.io/traefik/middlewares/http/headers/)) to the workspace Traefik config:

Here is an example config diff reflecting what this PR adds:
```diff
		  middlewares:
		    workspace27366e668ca645c9-auth:
		      forwardAuth:
		        address: http://127.0.0.1:8089?namespace=admin-che
		        trustForwardHeader: false
+		    workspace27366e668ca645c9-errors:
+		      errors:
+		        query: /
+		        service: che-dashboard
+		        status: 500-599
+		    workspace27366e668ca645c9-headers:
+		      headers:
+		        customResponseHeaders:
+		          cache-control: no-store, max-age=0
		    workspace27366e668ca645c9-strip-prefix:
		      stripPrefix:
		        prefixes:
		        - /workspace27366e668ca645c9
		  routers:
		    workspace27366e668ca645c9:
		      middlewares:
		      - workspace27366e668ca645c9-strip-prefix
		      - workspace27366e668ca645c9-auth
+		      - workspace27366e668ca645c9-headers
+		      - workspace27366e668ca645c9-errors
		      priority: 100
		      rule: PathPrefix(`/workspace27366e668ca645c9`)
		      service: workspace27366e668ca645c9
		    workspace27366e668ca645c9-3100-healthz:
		      middlewares:
		      - workspace27366e668ca645c9-strip-prefix
		      priority: 101
		      rule: Path(`/workspace27366e668ca645c9/theia-ide/3100/healthz`)
		      service: workspace27366e668ca645c9
+		  serversTransports:
+		    workspace27366e668ca645c9:
+		      forwardingTimeouts:
+		        dialTimeout: 4s
		  services:
		    workspace27366e668ca645c9:
		      loadBalancer:
		        servers:
		        - url: http://workspace27366e668ca645c9-service.admin-che.svc:3030
		        serversTransport: workspace27366e668ca645c9
```

The [serverTransport](https://doc.traefik.io/traefik/routing/services/#forwardingtimeoutsdialtimeout) config was added to add a 4 second timeout for when trying to access the workspace url. If the workspace server cannot be reached after 4 seconds, then, the `errors` middleware will kick in and redirect requests to the workspace url to the dashboard.

**Review by tolusha — APPROVED** [review]

**Review by ibuziuk — APPROVED** [review]

**Pull request merged**
