### PR TITLE
feat: set default components container image and default editor

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatolii Bazko <abazko@redhat.com>

### What does this PR do?
set default components container image and default editor

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/21554

### How to test this PR?

N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [Custom resource definition file is up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#updating-custom-resource-definition-file)
- [ ] [OLM bundles are up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#update-olm-bundle)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by olexii4** [comment]
@tolusha  Thank you very much for helping with https://github.com/eclipse/che/issues/21554
I have tested it. It works as expected. 
@ibuziuk @l0rd 
What do you think about new defaults?
```
    defaultComponents:
      - container:
          image: 'quay.io/devfile/universal-developer-image:ubi8-latest'
        name: universal-developer-image
    defaultEditor: che-incubator/che-code/insiders
```

**Review by olexii4 — APPROVED** [review]

**Review by ibuziuk — COMMENTED** [review]
Looks good to me in general, but I think @l0rd suggested using the tag instead of `latest` 
+ not sure if we need to additionally communicate the switch to che-code by default with the community

**Comment by l0rd** [comment]
> Looks good to me in general, but I think @l0rd suggested using the tag instead of `latest`
> 
>     * not sure if we need to additionally communicate the switch to che-code by default with the community

Yes please use theia as the default editor. We want the switch to happen when we are ready Dev Spaces side too (at least https://github.com/eclipse/che/issues/20500 should be completed): we want to avoid having 2 different defaults upstream and downstream for a long time. And yes we need to communicate about that.

**Comment by l0rd** [comment]
And about using a specific tag: I think it's ok for nightly to use `insiders` or `next` but when we do a release we should use a specific tag/version. cc @nickboldt @mkuznyetsov.

**Review by ibuziuk — APPROVED** [review]
thanks, @tolusha LGTM :+1:

**Comment by azatsarynnyy** [comment]
> > And about using a specific tag: I think it's ok for nightly to use `insiders` or `next` but when we do a release we should use a specific tag/version. cc @nickboldt @mkuznyetsov.
> 
> unlike other che-incubator/eclipse che projects, che-code doesn't have defined release workflow right now. I observe two workflows in it, one called `insiders`, that builds from pushes main branch, and one called `stable`, that builds from pushes to `1.y.z` format branches (which was not used since 8 months ago).

You're right @mkuznyetsov, we have only `next`/`insider` images published.
There's a task to setup a release job for Che-Code: https://github.com/eclipse/che/issues/21552

**Pull request merged**
