### PR TITLE
feat: Support node selector and pod tolerations in devworkspaces

### PR DESCRIPTION
**Pull request by metlos**
### What does this PR do?

This adds support for a couple of things:

* adds support for workspace pod tolerations and node selector as properties in
  the `CheCluster` CRD v1 under `spec.server.workspacePodTolerations` and `spec.server.workspacePodNodeSelector`
  in addition to the `CHE_WORKSPACE_POD_NODE__SELECTOR` and `CHE_WORKSPACE_POD_TOLERATIONS__JSON` custom
  properties,
* adds support for the same as properties in the CRD v2alpha1 under `spec.workspaces.podTolerations` and 
  `spec.workspaces.podNodeSelector`,
* implements conversion between the two (when converting to v2alpha1, the values are read out of either
  the properties, or if not found there, from the custom che properties)
* the usernamespace reconciler now annotates the user namespace/project with annotations understood by
  the devworkspace operator to apply the node selector and pod toleration configuration to the actual 
  devworkspace pods.

### Screenshot/screencast of this PR
none

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/20884

### How to test this PR?
1. Install the che-operator from this PR (I've pre-built an image `quay.io/lkrejci/che-operator:issue-20884`)
1. Configure node selector and/or pod tolerations in the CheCluster CR
1. Create a devworkspace
1. The configuration should be applied to the workspace pod

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [Custom resource definition file is up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#updating-custom-resource-definition-file)
- [x] [OLM bundles are up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#update-olm-bundle)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by metlos** [comment]
@tolusha, help please! How do I unblock the two stuck jobs?

**Comment by tolusha** [comment]
I don't know. We can wait or close/opene the PR (I hope it will work)

**Review by tolusha — APPROVED** [review]

**Pull request merged**
