### PR TITLE
Remove priority from container-build SCC

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
Remove the priority field from the container-build SCC that is created by Che. Previously this field was introduced to workaround issue https://github.com/devfile/devworkspace-operator/issues/884, and is no longer required since https://github.com/eclipse/che/issues/21770 is resolved.

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
Closes https://github.com/eclipse/che/issues/21959

### How to test this PR?
1. Install Che, enable container-build in CheCluster. Note that in current builds of Che, DevWorkspace Operator v0.18.0 and higher is required.
2. Create an SCC we _don't_ intend to use: https://gist.github.com/l0rd/87337c08ecf414499681261f9fbcebe2
3. Start a workspace and verify that container build works as intended; container-build SCC is used instead of the `restricted-runasuser` SCC created in step 2

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [Development resource are up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#update-development-resources)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by ibuziuk — COMMENTED** [review]
:+1:

**Review by ibuziuk — APPROVED** [review]
@tolusha we should backport it to 7.58.x to have it in 3.4 I believe

**Comment by ibuziuk** [comment]
after a discussion with @amisevsk looks like we also need to backport https://github.com/eclipse-che/che-operator/pull/1576 to 7.58.x

**Comment by amisevsk** [comment]
Specifically, backporting https://github.com/eclipse-che/che-operator/pull/1549 (which is part of #1576) is required if this PR is backported

**Comment by tolusha** [comment]
Should be closed in favor of https://github.com/eclipse-che/che-operator/pull/1606

**Pull request closed without merging**
