### PR TITLE
fix: update regexes for KIP default images

### PR DESCRIPTION
**Pull request by dkwon17**
Signed-off-by: David Kwon <dakwon@redhat.com>
(cherry picked from commit b4c6244b4f70b102267ee98c20b5fd8e72a27fe3)

### What does this PR do?
Backport for https://github.com/eclipse-che/che-operator/pull/1061

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [Custom resource definition file is up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#updating-custom-resource-definition-file)
- [ ] [OLM bundles are up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#update-olm-bundle)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by ibuziuk — APPROVED** [review]

**Review by nickboldt — APPROVED** [review]
LGTM, but with two questions:
* why are there no CRW tests? you have CRW-friendly regexes, but no CRW-validating tests
* you use regexs that specirically look for machine exec and a handful of stacks/sidecars. But all these stacks/sidecars end in `_plugin_registry_image`, so why not use an even simpler regex to pull ALL `_plugin_registry_image` named env vars? Same question for `_devfile_registry_image` env vars?

**Comment by tolusha** [comment]
Tests failed:
```
--- FAIL: TestEnvVars (0.14s)
    --- FAIL: TestEnvVars/detect_plugin_broker_images (0.03s)
    --- FAIL: TestEnvVars/detect_theia_images (0.03s)
    --- FAIL: TestEnvVars/detect_machine_exec_image (0.02s)
    --- FAIL: TestEnvVars/detect_plugin_registry_images (0.04s)
    --- FAIL: TestEnvVars/detect_devfile_registry_images (0.03s)
```

**Comment by dkwon17** [comment]
@nickboldt you're right, the regexes could have better test coverage. I plan to provide another PR to main, and will cherry pick to this PR.

Using a regex to pull all `_plugin_registry_image ` and `_devfile_registry_image` images would pull too many images for Che: https://github.com/eclipse-che/che-operator/blob/a1f30c335626a0a3632ff38beeaea6ed1d053ba2/bundle/stable/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml#L994-L1107

**Comment by dkwon17** [comment]
Thank you everyone for the feedback. After cherry-picking https://github.com/eclipse-che/che-operator/commit/a793896191bdfe5a34bdf3f74eaa255404de60ee, tests now pass:
```
--- PASS: TestEnvVars (0.07s)
    --- PASS: TestEnvVars/detect_plugin_broker_images (0.01s)
    --- PASS: TestEnvVars/detect_theia_images (0.02s)
    --- PASS: TestEnvVars/detect_machine_exec_image (0.02s)
    --- PASS: TestEnvVars/detect_plugin_registry_images (0.01s)
    --- PASS: TestEnvVars/detect_devfile_registry_images (0.01s)
```

**Review by tolusha — APPROVED** [review]

**Pull request merged**
