### PR TITLE
Build restic binary from source

### PR DESCRIPTION
**Pull request by mmorhun**
Signed-off-by: Mykola Morhun <mmorhun@redhat.com>

### What does this PR do?
Downloads license file for restic binary

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/20028

### How to test this PR?
Run built image and navigate to `/usr/local/bin`

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [Custom resource definition file is up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#updating-custom-resource-definition-file)
- [ ] [Nightly OLM bundle is up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#update-nightly-olm-bundle)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### CODE REVIEW

**Review by AndrienkoAleksandr — APPROVED** [review]

**Review by nickboldt — CHANGES_REQUESTED** [review]
cannot simply ADD a remote URL in a Brew build, so curling the file and having it in the builder stage would make this easier to downstream.

Even better, if your builder stage can fetch the whole project from a specific tag & build it in the builder stage, then you can simply copy the binary + license file to the runtime stage.

By doing that, we solve two issues:
a) downstreamability
b) built from source (so in case of serious bugs, we can patch our version of the sources and include the fix in Che and CRW, without having to rely on restic devs to release a new version)

**Review by nickboldt — APPROVED** [review]
+1, but see comments on https://github.com/che-dockerfiles/che-backup-server-rest/pull/2/files re: using micro or scratch for the runtime image.

**Comment by mmorhun** [comment]
@nickboldt thank you for the review. However, I believe that replacing base image of the operator should be done in another PR.

**Pull request merged**
