### PR TITLE
feat: Don't deploy CheManager - it no longer is a thing

### PR DESCRIPTION
**Pull request by metlos**
### What does this PR do?
This PR changes the devworkspace deployment and doesn't deploy the `CheManager` resource, which the DWCO is phasing out. This should be merged RIGHT AFTER https://github.com/che-incubator/devworkspace-che-operator/pull/49 is merged.

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
eclipse/che#19847

### How to test this PR?
1. There is a test image of DWCO built from https://github.com/che-incubator/devworkspace-che-operator/tree/issue-19847
2. Build che-operator from this PR that sources the deployment files from the above DWCO:
```
export IMAGE="quay.io/lkrejci/che-operator:issue-19847" && docker build -t $IMAGE --build-arg=DEV_WORKSPACE_CHE_OPERATOR_VERSION=issue-19847 --no-cache . && docker push $IMAGE
```
(replace `quay.io/lkrejci/che-operator:issue-19847` with your image name or you can actually just use that image and skip this step, if you want to).

3. Deploy the previously built `che-operator` to an OpenShift cluster, e.g.: `chectl server:deploy -p openshift -a operator --che-operator-image=quay.io/lkrejci/che-operator:issue-19847` (replacing the operator image with your image name, if you rebuilt manually)
4. Enabled devworkspaces in the `CheCluster` CR.
5. Check there is no `CheManager` resource in the cluster (not even the `chemanagers.che.eclipse.org` CRD)
5. Deploy some devfile v2 workspace.
6. Observe the workspace starting and working as expected.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [Custom resource definition file is up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#updating-custom-resource-definition-file)
- [x] [Nightly OLM bundle is up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#update-nightly-olm-bundle)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by tolusha — APPROVED** [review]

**Comment by tolusha** [comment]
related to [1]
If this PR is merged before [1] then we have to adapt [1] and vice versa.

[1] https://github.com/eclipse-che/che-operator/pull/745

**Review by AndrienkoAleksandr — APPROVED** [review]

**Review by mmorhun — APPROVED** [review]

**Pull request merged**
