### PR TITLE
feat: Import Devworkspace Che Operator

### PR DESCRIPTION
**Pull request by metlos**
### What does this PR do?
This imports the Devworkspace Che Operator as a new controller inside `che-operator`.

The minimum amount of changes have been made to both codebases for the stuff to work.
In another words, the new controller `pkg/controller/devworkspace` is essentially still
completely standalone. It even still runs in its own reconcile loop even though it
reconciles `CheCluster` which is also reconciled by the main `che` controller.

The significant changes are are concentrated in `cmd/manager/main.go`, which sets the whole
show up.

In `pkg/deploy/dev-workspace`, we have a new approach for installing the devworkspace support.
The operator exits after a successfull installation, relying on Kubernetes to restart it.
When intialized again, it sees the CRDs for devworkspaces present in the cluster and
initializes the devworkspace reconciler.

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
eclipse/che#19408

### How to test this PR?
1. Install che-operator
1. Remove the DWCO container for the che-operator deployment (not yet done in this PR)
1. Change the che-operator image to `quay.io/lkrejci/che-operator:issue-19408`
1. Enable devworkspaces in the CheCluster CR
1. Notice the che-operator restart automatically after installation of Devworkspaces
1. Try to create a devfile v2.
1. Rejoice.

### PR Checklist
          
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [Custom resource definition file is up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#updating-custom-resource-definition-file)
- [ ] [Nightly OLM bundle is up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#update-nightly-olm-bundle)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by metlos** [comment]
For the CI to pass, we may need https://github.com/devfile/devworkspace-operator/pull/504 merged (depending on the version of minikube we're using).

**Comment by metlos** [comment]
Hmm... so this boils down to the difference in `k8s.io/api` version in che-operator (0.20.6) vs devworkspace-operator (0.18.8).

**Comment by tolusha** [comment]
@metlos 
Could you fix conflicts pls? I would like to proceed.

**Comment by metlos** [comment]
@sparkoo, @skabashnyuk could you please take a look?

**Comment by tolusha** [comment]
It seems we have more issues with OpenShift, I will keep investigation

**Comment by tolusha** [comment]
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/eclipse-che_che-operator/925/pull-ci-eclipse-che-che-operator-main-v7-multi-host-next-deployment/1422936456984268800/artifacts/multi-host-next-deployment/gather-extra/artifacts/pods/eclipse-che_che-operator-8d5487cc5-84wk2_che-operator.log

`time="2021-08-04T16:00:38Z" level=fatal msg="Failed to initialize default value: 'RELATED_IMAGE_devworkspace_che_operator'. Environment variable with default value was not found."`

It seems the `quay.io/eclipse/che-operator:next` is used instead of one built from the current branch.

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/eclipse-che_che-operator/925/pull-ci-eclipse-che-che-operator-main-v7-multi-host-next-deployment/1422936456984268800/artifacts/multi-host-next-deployment/gather-extra/artifacts/pods.json

**Comment by tolusha** [comment]
@metlos 
pls rebase.

**Comment by sparkoo** [comment]
> @metlos
> pls rebase to proceed

I'll do it. Lukas is on PTO so I'm working on this now.

**Comment by tolusha** [comment]
`v7-stable-to-nightly` it is expected to fail  (https://github.com/eclipse/che/issues/20235)

**Comment by tolusha** [comment]
`ci/prow/v8-multi-host-next-deployment` 
`ci/prow/v8-single-host-next-deployment`

Failed with

`echo 'Failed to run pods in devworkspace-controller-test'`

**Comment by sparkoo** [comment]
> `ci/prow/v8-multi-host-next-deployment`
> `ci/prow/v8-single-host-next-deployment`
> 
> Failed with
> 
> `echo 'Failed to run pods in devworkspace-controller-test'`

What does it actually mean? Is it an issue of the PR or is it CI?
I'm sorry if it is obvious, but I can't read the test logs, I don't know what the tests are doing.

**Comment by AndrienkoAleksandr** [comment]
Hello @sparkoo . I checked new dependencies from this pr. Result in the gist https://gist.github.com/AndrienkoAleksandr/33b7525e911a538a1d81342514c24203
So 10 dependencies are green, one we can skip, because it's golang standart lib. For 2 dependencies we have to create CQ, because bad license rate in the clearlydefined.io. And for 8 we have two options: create clearlydefined curration or create CQ.

**Comment by tolusha** [comment]
Workspace created by script [1] is not started. PVC is in pending state

screenshot-console-openshift-console apps ci-ln-m0hgnc2-f76d1 origin-ci-int-gce dev openshift com-2021 08 05-16_11_08
screenshot-console-openshift-console apps ci-ln-m0hgnc2-f76d1 origin-ci-int-gce dev openshift com-2021 08 05-16_10_22




[1] https://github.com/metlos/che-operator/blob/dwco-merge/.github/bin/common.sh#L494-L507

**Comment by skabashnyuk** [comment]
>https://github.com/eclipse-che/che-operator/pull/925#issuecomment-893435425 

I can handle that

**Comment by tolusha** [comment]
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/eclipse-che_che-operator/925/pull-ci-eclipse-che-che-operator-main-v7-stable-to-nightly/1423981878754414592/artifacts/stable-to-nightly/stable-to-nightly/artifacts/eclipse-che/che-operator-687f7b5599-dppmc/che-operator.log

```
E0807 14:02:57.890476       1 reflector.go:138] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to watch *v1alpha1.KubernetesImagePuller: failed to list *v1alpha1.KubernetesImagePuller: kubernetesimagepullers.che.eclipse.org is forbidden: User "system:serviceaccount:eclipse-che:che-operator" cannot list resource "kubernetesimagepullers" in API group "che.eclipse.org" at the cluster scope
```

**Comment by skabashnyuk** [comment]
- [ ] github.com/gliderlabs/ssh v0.2.2 https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23642
- [ ] github.com/emirpasic/gods v1.12.0 https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23643	
- [ ] github.com/go-git/go-billy v5.0.0 https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23644
- [ ] github.com/jbenet/go-context d14ea06fba99483203c19d92cfcd13ebe73135f4 https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23645
- [ ] github.com/kevinburke/ssh_config 01f96b0aa0cdcaa93f9495f89bbc6cb5a992ce6e https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23646
- [ ] github.com/lucasjones/reggen 37ba4fa293bb40d3e1d805ba3545bfaab688d669 https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23647
- [ ] github.com/redhat-cop/operator-utils v0.1.0 https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23648
- [ ] github.com/devfile/api  v2.0.0  https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23649
- [ ] github.com/devfile/devworkspace-operator	108b1f1fbe4574f1a47a7810b7d877684785a6d9 	https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23650

**Comment by sparkoo** [comment]
> https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/eclipse-che_che-operator/925/pull-ci-eclipse-che-che-operator-main-v7-stable-to-nightly/1423981878754414592/artifacts/stable-to-nightly/stable-to-nightly/artifacts/eclipse-che/che-operator-687f7b5599-dppmc/che-operator.log
> 
> ```
> E0807 14:02:57.890476       1 reflector.go:138] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to watch *v1alpha1.KubernetesImagePuller: failed to list *v1alpha1.KubernetesImagePuller: kubernetesimagepullers.che.eclipse.org is forbidden: User "system:serviceaccount:eclipse-che:che-operator" cannot list resource "kubernetesimagepullers" in API group "che.eclipse.org" at the cluster scope
> ```

I've tested update from 7.34.0 into this PR version, and it works fine. However, I don't know details of the CI test deployment. I don't have imagepuller enabled (I guess, I don't know how to do it). 
It's very hard to get something from the CI.

**Comment by tolusha** [comment]
I will take a look `ci/prow/v7-stable-to-nightly`

**Comment by tolusha** [comment]
Here is a test script which is run on OpenShift CI. 
So, it starts requiring cluster roles now [2]. I think a fix will be a pretty simple. But I would like to know why these changes are required now.

[1] https://github.com/eclipse-che/che-operator/blob/main/.ci/oci-nightly-update.sh
[2] https://github.com/eclipse-che/che-operator/blob/main/config/rbac/role.yaml#L121-L126

**Comment by skabashnyuk** [comment]
@tolusha @metlos @sparkoo https://github.com/eclipse-che/che-operator/pull/925#issuecomment-894694600 all CQs has been approved.

**Pull request merged**
