### PR TITLE
feat: allow not to set resources requests/limits

### PR DESCRIPTION
**Pull request by tolusha**
### What does this PR do?
Allows not to set resources requests/limits:
- if resource requests/limits is set, then use it
- if resource requests/limits is not set, then default will be set
- if resource requests/limits is zero ('0"), then value won't be set (no requests/limits)

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/22036

### How to test this PR?

N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [Development resource are up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#update-development-resources)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by ibuziuk — APPROVED** [review]
LGTM, I am just not sure that setting '0' for applying no limits is good from the semantics perspective 
@l0rd wdyt?

**Comment by l0rd** [comment]
> LGTM, I am just not sure that setting '0' for applying no limits is good from the semantics perspective @l0rd wdyt?

I have the same concern. The original idea was to use strategic merge patch syntax as we do on the devfile side and where there is a standard way to support that. But CheCluster deployment doesn't have the full kube Deployments fields and that's not possible to use that syntax and that's ok because we want to keep CheCluster simple. But using zero to mean "do not specify" is kind of awkward. @amisevsk what do you think?

**Review by amisevsk — APPROVED** [review]

**Comment by amisevsk** [comment]
I think using "0" as "no limit" isn't ideal, but I don't see a better option with resource.Quantity. Strategic merge patch syntax is handy, but also requires much more explanation (deleting a field requires a special markup, etc. and the process generally requires an idea of what the defaults are).

I believe (but haven't fully confirmed) that specifying "0" for a resource field on a pod behaves the same way as leaving it empty.

**Comment by tolusha** [comment]
@amisevsk 
if a value is `0` in a CheCluster, then che-operator sets nothing for a container resource field. 
if a value is empty in a CheCluster, then che-operator sets a default value depending on the component.

**Comment by tolusha** [comment]
Another option is to populate CheCluster with defaults values for all components like this [1]. Once value is removed from CheCluster, then che-operator will remove it from container resource field. 

[1]: 
```
  components:
    pluginRegistry:
      deployment:
        containers:
          - resources:
              request:
                cpu: '50m'
                memory: '100Mi'
              limits:
                cpu: '50m'
                memory: '100Mi'
    devfileRegistry:
      deployment:
        containers:
          - resources:
              request:
                cpu: '50m'
                memory: '100Mi'
              limits:
                cpu: '50m'
                memory: '100Mi'
    cheServer:
      deployment:
        containers:
          - resources:
              limits:
                cpu: '600m'
                memory: '100Mi'
    dashboard:
      deployment:
        containers:
          - resources:
              request:
                cpu: '50m'
                memory: '100Mi'
              limits:
                cpu: '50m'
                memory: '100Mi'
    database:
      deployment:
        containers:
          - resources:
              request:
                cpu: '50m'
                memory: '100Mi'
              limits:
                cpu: '50m'
                memory: '100Mi'
  networking:
    auth:
      gateway:
        deployment:
          containers:
            - name: gateway
              resources:
                request:
                  cpu: '50m'
                  memory: '100Mi'
                limits:
                  cpu: '50m'
                  memory: '100Mi'
            - name: configbump
              resources:
                request:
                  cpu: '50m'
                  memory: '100Mi'
                limits:
                  cpu: '50m'
                  memory: '100Mi'
            - name: oauth-proxy
              resources:
                request:
                  cpu: '50m'
                  memory: '100Mi'
                limits:
                  cpu: '50m'
                  memory: '100Mi'
            - name: kube-rbac-proxy
              resources:
                request:
                  cpu: '50m'
                  memory: '100Mi'
                limits:
                  cpu: '50m'
                  memory: '100Mi'
```

**Comment by l0rd** [comment]
> I personally, like the idea of explicit requests and limits in the CR more, the only downside is that it makes the yaml bigger

But that goes against the good practice that wants an empty CR to correspond to the default values  (this is the feedback we got for CRW and that we have tried to address with CheCluster v2).

If @tolusha and @amisevsk are ok with the semantic of using zero to mean unset I am ok too.

**Comment by ibuziuk** [comment]
makes sense, I approved the PR in the current state

**Pull request merged**
