### PR TITLE
Updating go (to match Dockerfile) and golang.org/x/net

### PR DESCRIPTION
**Pull request by SDawley**
### What does this PR do?
Dockerfile uses go 1.19.13, but go mod file still said go 18, updating to match.
Should resolve [CRW-3891](https://issues.redhat.com/browse/CRW-3891) and [CRW-3618](https://issues.redhat.com/browse/CRW-3618) (technically already done I guess).
Updating golang.org/x/net for [CRW-4654](https://issues.redhat.com/browse/CRW-4654)

### How to test this PR?
Built the Dockerfile locally

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [Development resource are up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#update-development-resources)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by SDawley** [comment]
retest

**Comment by tolusha** [comment]
@SDawley 
I am a bit confused.
Is it the purpose to update some dependencies or completely switch to go 1.19?

**Comment by SDawley** [comment]
Both

**Review by nickboldt — APPROVED** [review]
failing tests appear to be:
* formatting change to add more spaces in comments
* formatting change to add more spaces in comments
* 71 of 73 prow tests passed; the other two timed out, as they like to do. 
Therefore +1 to merge this.

**Pull request merged**
