### PR TITLE
chore: Limit new all-namespaces-stable channel to OpenShift 4.8+

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatolii Bazko <abazko@redhat.com>

### What does this PR do?
Limit new all-namespaces-stable channel to OpenShift 4.8+
see docs: 
https://redhat-connect.gitbook.io/certified-operator-guide/ocp-deployment/operator-metadata/bundle-directory/managing-openshift-versions

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/20234

### How to test this PR?

N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [Custom resource definition file is up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#updating-custom-resource-definition-file)
- [ ] [OLM bundles are up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#update-olm-bundle)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by mmorhun — APPROVED** [review]

**Review by AndrienkoAleksandr — APPROVED** [review]

**Comment by nickboldt** [comment]
Does this change actually work? Asking because https://issues.redhat.com/browse/CRW-2138 suggests to me that we can't set a version other than 4.5 (old format appstream) or 4.6 (new format iib bundle).

**Comment by tolusha** [comment]
@nickboldt 
Maybe because of that
```
NOTE: Commas are generally not allowed, and should not be used. For historical reasons, there are two special values that are currently allowed, v4.5,v4.6 and v4.6,v4.5. Both behave as just v4.5. The operator is supported on the v4.5 version of OpenShift or later. Any other usage of commas, e.g. v4.6,v4.7, will prevent the operator from being added to the certified catalog.
```

**Comment by tolusha** [comment]
I don't see why v4.8 won't work.

**Comment by tolusha** [comment]
Doc  [1] proves that `LABEL com.redhat.openshift.versions="v4.8"` works. What is missed is annotation.

[1] https://access.redhat.com/documentation/en-us/openshift_container_platform/4.8/html-single/operators/index

**Pull request merged**
