### PR TITLE
fix: ingress annotation when single-host and gateway exposure

### PR DESCRIPTION
**Pull request by disaster37**
### What does this PR do?

It add ingress annotation `'nginx.ingress.kubernetes.io/proxy-buffer-size: 16k` when deploy eclipse-che with `single-host` and `gateway` exposure. It avoid `502 bad gateway` with long headers provided by keykloack.

### What issues does this PR fix or reference?

Fix this issue [#20781](https://github.com/eclipse/che/issues/20781)

### How to test this PR?

I have tested with this steps:
```bash
chectl server:deploy --installer=operator --domain=che-pull-request.rancher-hpd.hm.dm.ad --multiuser --chenamespace=che-pull-request --cheboottimeout=600000 --platform=k8s --che-operator-cr-patch-yaml=che-operator-cr-patch.yaml --postgres-pvc-storage-class-name=nfs-client --workspace-pvc-storage-class-name=nfs-client --che-operator-image=disaster/che-operator:pr-annotation-gateway --skip-kubernetes-health-check
```

che-operator-cr-patch.yaml
```yaml
spec:
  k8s:
    singleHostExposureType: 'gateway'
    tlsSecretName: 'che-tls-certificates'
  metrics:
    enable: false
  server:
    serverExposureStrategy: 'single-host'
    proxyPort: "8080"
    proxyURL: 'http://squid.squid.svc.cluster.local'
    nonProxyHosts: 'localhost|10.0.0.0/8|.hm.dm.ad|.rancher-hpd.hm.dm.ad|.svc.cluster.local'
    useInternalClusterSVCNames: true
    workspaceNamespaceDefault: 'che-<username>'
    #externalDevfileRegistry: true
    #externalPluginRegistry: true
    customCheProperties:
      CHE_LIMITS_USER_WORKSPACES_COUNT: "-1"
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: "3"
      CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: "43200000"
      CHE_INFRA_KUBERNETES_NAMESPACE_ANNOTATIONS: 'che.eclipse.org/username=<username>,field.cattle.io/projectId=c-57d7n:p-8j45h'
      CHE_INFRA_KUBERNETES_NAMESPACE_LABELS: 'app.kubernetes.io/part-of=che.eclipse.org,app.kubernetes.io/component=workspaces-namespace,field.cattle.io/projectId=p-8j45h'
      CHE_WORKSPACE_DEFAULT__CPU__LIMIT__CORES: '1'
      CHE_WORKSPACE_DEFAULT__CPU__REQUEST__CORES: '500m'
      CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__LIMIT__CORES: '300m'
      CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__REQUEST__CORES: '50m'
  storage:
    pvcClaimSize: 4Gi
    pvcStrategy: per-workspace
```

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [Custom resource definition file is up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#updating-custom-resource-definition-file)
- [ ] [OLM bundles are up to date](https://github.com/eclipse-che/che-operator/blob/main/README.md#update-olm-bundle)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by tolusha** [comment]
@disaster37 
Thank you for contribution. Pls revert all changes in crd files.
Other than that sounds good.

**Comment by disaster37** [comment]
I have doing hard reset. I doesn't understant how CRD files has been modified ... Sorry for that

**Review by tolusha — APPROVED** [review]

**Comment by tolusha** [comment]
@disaster37 
Image build failed.
1. Try `make test` to ensure that all tests passed
2. Try `docker build .` to ensure image can be built

**Comment by disaster37** [comment]
Hi already look that many tests failed, but is not linking with my change so ... (I have also tested to run test on main branch without change and test failed)
If I test only ingress, it's work fine, (aka `go test ./... -v -run "TestIngressSpec"` and `go test ./... -v -run "TTestSyncIngressToCluster"`

**Comment by tolusha** [comment]
Hi.
```
go test ./... -v -run "TestIngressSpec" 

...
=== RUN   TestIngressSpec/Test_custom_host#01
--- FAIL: TestIngressSpec (0.00s)
    --- FAIL: TestIngressSpec/Test_custom_host (0.00s)
    --- PASS: TestIngressSpec/Test_custom_host#01 (0.00s)
FAIL
FAIL	github.com/eclipse-che/che-operator/pkg/deploy	0.701s
....

```

**Comment by disaster37** [comment]
Hum,

it very strange. On my workspace is run fine:

```bash
=== RUN   TestIngressSpec
=== RUN   TestIngressSpec/Test_custom_host
=== RUN   TestIngressSpec/Test_custom_host#01
--- PASS: TestIngressSpec (0.00s)
    --- PASS: TestIngressSpec/Test_custom_host (0.00s)
    --- PASS: TestIngressSpec/Test_custom_host#01 (0.00s)
```

**Comment by tolusha** [comment]
I think project location does matter.

`GOPATH=/home/tolusha/gocode`
project path: `~/gocode/src/github.com/eclipse-che/che-operator`

**Comment by disaster37** [comment]
Hi, there is a chance to merge it ?

**Comment by tolusha** [comment]
@disaster37 
There are changes in crd files again.
Pls revert them.

**Comment by disaster37** [comment]
Hum, i doesn't understand how it's possible.
I have recreate branch from upstream/main and add fix on it. Now there are only the 2 files modified

**Pull request merged**
